[package]
name = "bevy-3d-fps-survival"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_editor_pls = "0.8.1"
bevy_quinnet = "0.7.0"
